# original command
# docker run --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j-test1/data:/data --volume=$HOME/neo4j-plugins:/var/lib/neo4j/plugins --ulimit=nofile=40000:40000 -d neo4j:3.3.5-enterprise
version: '3'

services:
  
  neo4j:
    image: 13.232.214.47:5000/neo4j:3.3.5-enterprise
    # restart: unless-stopped
    environment:
        # provide your credentials here
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"
      - "7687:7687"
    # ulimits:
      # nproc: 40000
      # nofile:
        # soft: 40000
        # hard: 40000
    volumes:
      - /Users/arnab/Inventa/Server/docker-swarm-neo4j-enterprise-3.3.5/data:/data
      - /Users/arnab/Inventa/Server/docker-swarm-neo4j-enterprise-3.3.5/neo4j-plugins:/var/lib/neo4j/plugins
    # command: mongod
